### ISSUE TITLE
User-controllable zoom

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#238]
A feature request: user-controlled zoom for the Preview pane, using ctrl+mouse wheel, or ctrl + / ctrl - / ctrl 0, or in the Settings dialog. I often teach using the Preview pane and like to zoom the text so students in the back row can see it. Something like `self._widget.webView.page().mainFrame().setZoomFactor(new_zoom_factor)` .

**Comment by hlamer** [comment]
Done

**Comment by bjones1** [comment]
Fantastic! I would suggest one change: the zoom "direction" is backwards: Ctrl+wheel up makes the text smaller, instead of bigger, and vice versa.

**Comment by hlamer** [comment]
oops, inverted
