### ISSUE TITLE
Support more encoding.

### ISSUE THREAD

**Issue by srazi** [hlamer/enki#249]
First thank you for your great application, I like Enki. I would love it If it was based on Qt and C++ :-D

On Windows `Notepad` can save/read files with the following encodings:
`ANSI,
Unicode,
Unicode big endian,
UTF-8`

After some research I found that `Unicode` is `UTF-16LE` and `Unicode big endian` is `UTF-16BE` and `ANSI` means system default encoding for example for western version it is `windows-1252` and for my installed version of Windows (support Persian) it is `windows-1256`.

Is it possible to support opening file with these encodings?

Unfortunately I don't know python but maybe something like the following code works:

```python
try:
    text = unicode(data, 'utf8')
except UnicodeDecodeError, ex:
    try:
        text = unicode(data, 'utf_16_le')
    except UnicodeDecodeError, ex:
        try:
            text = unicode(data, 'utf_16_be')
        except UnicodeDecodeError, ex:
            try:
                text = unicode(data, 'windows-1256')
            except UnicodeDecodeError, ex:
                QMessageBox.critical(None,
                                     self.tr("Can not decode file"),
                                     filePath + '\n' +
                                     '\nProbably invalid encoding was set. ' +
                                     'You may corrupt your file, if saved it')
                text = unicode(data, 'utf8', 'replace')
```

**Comment by hlamer** [comment]
Hi

Encodings are huge and complicated topic.

There are many cases, when it is impossible to detect charset reliably, so, manual selection on GUI is necessary.

Notepad has 1 way to open files (probably 2, dialogue and cmdline). Enki is much more complicated. It opens files with open dialogue, with cmdline, with FileBrowser, with Locator, when searching in directory, when restoring session and probably some other cases. I wouldn't like to add charset selection in all this places, because I'd like to keep the GUI as simple as possible.

Except this, I'm a non-utf8 charset hater, and by supporting only utf8 I contribute to other charsets death.

Just use some other tools to convert your files to utf8.

**Comment by srazi** [comment]
Hello,

> Except this, I'm a non-utf8 charset hater, and by supporting only utf8 I contribute to other charsets death.

Windows uses `UTF16` for unicode then I think at least `utf-16` will be alive always ;-)

BTW, do you think code in my first comment is a workaround for this issue? because then I can provide a development environment and compile it by myself.

**Comment by hlamer** [comment]
Enki is supposed to be used mainly for coding. You can store utf-8 source files on Windows file system, edit it in Windows. Compilers, interpreters, browsers would understand your files, your colleagues which use non-Windows and live in another countries would be thankful to you.
Just don't try to open sources with Notepad. It is not important, what Windows uses.

**Comment by srazi** [comment]
Thanks but that was not the answer to my question and I know about these things... and I don't open sources with Notepad there are Qt Creator, Visual Studio IDE and Notepad++ and etc...

Indeed my default editor was always Notepad++ but because it doesn't have a good Unicode bi-directional support I want to switch to a new editor, Enki is good if it supports a wider range of encodings (indeed it is (was) very easy because Qt Developers have implemented the hard part see [QTextStream::setAutoDetectUnicode()](http://qt-project.org/doc/qt-4.8/qtextstream.html#setAutoDetectUnicode)).
