### ISSUE TITLE
Ubuntu 14.04，run  ./bin/enki got error

### ISSUE THREAD

**Issue by supergis** [hlamer/enki#250]
I am using Ubuntu 14.04，run  ./bin/enki,got error:
ASSERT: "window" in file /build/buildd/appmenu-qt-0.2.7+14.04.20140305/src/appmenuplatformmenubar.cpp, line 349
已放弃 (核心已转储)

**Comment by hlamer** [comment]
I just
* installed 14.04 desktop.
* installed the dependencies
* cloned Enki and Qutepart
* installed Qutepart to the system
* run `./bin/enki`

All is fine for me.
How is your system different from mine?

**Comment by hlamer** [comment]
Can not reproduce without help

**Comment by afb** [comment]
I got the same crash, unless first disabling the Unity menubar:
export QT_X11_NO_NATIVE_MENUBAR=1

**Comment by hlamer** [comment]
@afb, now are are having main menu on Enki top tool bar.
Try to set `UBUNTU_MENUPROXY=1` instead of `QT_X11_NO_NATIVE_MENUBAR=1`. In this case the menu will be embedded to Unity tool bar, just like all other applications. Which variant do you like more?

**Comment by afb** [comment]
Right, that  works better. It does leave the menubar somewhat "blank", but it doesn't assert anymore...
I tried another editor called TEA*, which filled up the empty space with toolbar icons instead. Possibility ?
So the global menu is preferred (on Ubuntu), but maybe the info should be moved to the bottom then.

* https://apps.ubuntu.com/cat/applications/tea/  (from http://tea-editor.sourceforge.net/)

**Comment by hlamer** [comment]
@afb, 
* close all Enki instances
* do `rm ~/.config/enki/main_window_state.bin`, then 
* check current master.

I hope you'll like it.
