### ISSUE TITLE
Codechat package not installed or not found

### ISSUE THREAD

**Issue by ejlmljt** [hlamer/enki#252]
Windows 7 32 bit
Installed codechat
    cd python27\scripts pip install codechat
    Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32
   Type "copyright", "credits" or "license()" for more information.
    >>> import CodeChat
    >>> 
Installed from Enki-v14-07-2.exe.exe
Ran enki
    settings.settings.codechat 
        Check box greyed out
        The codechat program is not installed or is not found
Other complication:
    python33 also installed but:
        C:\Python27\Lib\site-packages\CodeChat>python -V
        Python 2.7.3

**Comment by bjones1** [comment]
That Enki release didn't include CodeChat and won't find it if pip installed. I've built a Windows binary from today's master which includes CodeChat. Would you try this?

https://dl.dropboxusercontent.com/u/2337351/Install_Enki.exe

**Comment by hlamer** [comment]
@ejlmljt, are you happy with this version? Can I close the issue?

**Comment by ejlmljt** [comment]
Hi Andrei,
Thanks for the email. I am going to test it at work this morning and will
let you know . Thanks
Eugene

**Comment by ejlmljt** [comment]
Thanks Adrei
I removed the previous version and installed your new version and Enki is
working properly.
Thanks for the speedy resolution!
Eugene

**Comment by hlamer** [comment]
Thanks to @bjones1 !
