### ISSUE TITLE
Icons for "Externally deleted" and "Externally modified" are too similar.

### ISSUE THREAD

**Issue by vi** [hlamer/enki#253]
One is big red diagonall cross, the other is white diagonal cross in a red circle respectively: ![del](https://cloud.githubusercontent.com/assets/173219/6192727/1031f2e8-b3c6-11e4-828c-0975c7e1e6fe.png)

I suggest the "Externally modified" symbol can be a red pencil instead: https://commons.wikimedia.org/wiki/File:Red_pencil.svg

**Comment by hlamer** [comment]
I like the idea!

**Comment by vi** [comment]
Shall there also be an icon for "diverged" case? I.e. both externally edited and unsaved. 

Options for the icon:
*  [red trident](http://pixabay.com/en/trident-fork-halloween-weapon-151565/) (but more diagonal; in in opposite direction to the pen);
* Bold red Github's fork symbol;
* [This](http://pixabay.com/en/divergent-arrows-left-right-fork-154512/) road divergence symbol, but filled and red;

**Comment by hlamer** [comment]
How about red cross (like now) over floppy?

**Comment by vi** [comment]
So there is already a special symbol for "Locally + Externally modified"? OK.

It is not red cross over floppy. It is like this:  ![sc](https://cloud.githubusercontent.com/assets/173219/6220214/d1e77176-b644-11e4-98d8-69d8ee0544d7.png)

Trying to interpret various versions of the icon:
* Little red cross over sheet of paper ![sc](https://cloud.githubusercontent.com/assets/173219/6220214/d1e77176-b644-11e4-98d8-69d8ee0544d7.png):
    * Error in document
    * Deleted content in document
* Floppy with a red diagonal cross 
![fl](https://cloud.githubusercontent.com/assets/173219/6220262/6c3e44e8-b645-11e4-9974-926f701fa1f3.png):
    * The document could not be saved;
    * The document has disappeared;
* Red floppy ![rf](https://cloud.githubusercontent.com/assets/173219/6220319/169f0a4e-b646-11e4-84b7-0d1179c74fd5.png):
    * Document is unsaved, but there's also something special that requires attention;
* Red divergence ![rd](https://cloud.githubusercontent.com/assets/173219/6220453/7dd49a48-b647-11e4-8658-075e50ec5236.png):
    * There is something requiring attention and there are two options.

I vote for the red floppy or road divergense symbol.

**Comment by hlamer** [comment]
@vi, could you make a bigger red floppy icon?
Current save icon is 22x22, but red save icon is 17x16

**Comment by hlamer** [comment]
Red floppy applied.
I tried to use the red pencil, but it is not recognizable as a pencil on a small 22 px icon.

**Comment by vi** [comment]
The icon still needs to be changed.

I'll try to make some suitable variant. Which license should the icon have? Does CC-BY-<b>NC</b>-SA suit?

**Comment by hlamer** [comment]
It does, but not desirable. Who knows which use is commercial from lawyers point of view.

-----Исходное сообщение-----
От: "Vitaly Shukela" <notifications@github.com>
Отправлено: ‎23.‎02.‎2015 17:54
Кому: "hlamer/enki" <enki@noreply.github.com>
Копия: "Andrei Kopats" <hlamer@tut.by>
Тема: Re: [enki] Icons for "Externally deleted" and "Externally modified"are too similar. (#253)

The icon still needs to be changed.
I'll try to make some suitable variant. Which license should the icon have? Does CC-BY-NC-SA suit?

**Comment by vi** [comment]
Here are more 22x22 icons:

* Save icon and deleted icon superimposed: ![savedel](https://cloud.githubusercontent.com/assets/173219/6338529/95c74fb4-bbc0-11e4-8099-887f965bc7b2.png)  
    Additive icon for additive situation: externally deleted + unsaved.
* Red exclamation mark: ![exlmark](https://cloud.githubusercontent.com/assets/173219/6338558/d2110474-bbc0-11e4-90bf-e61484339c4f.png)  
    Something important about this file. Don't know the use case, maybe "externally modified", maybe "failed to save this file";
* Red pencil, v2: ![redpencil](https://cloud.githubusercontent.com/assets/173219/6338599/1637caf2-bbc1-11e4-873d-67f449ed735f.png)  
    Created in Krita from scratch, license is the same as Enki's.  
    For "externally modified" alone.

**Comment by vi** [comment]
There can also be a lock icon for readonly files. Is it a good idea?

**Comment by hlamer** [comment]
>  Save icon and deleted icon superimposed

I've added this icon. However on my list of opened files it looks like a cross. Save icon is not recognizable. Could you try to make narrower cross? Try `icons/close.png`

>  Red exclamation mark

Would be cool to use it when failed to save file. But in this case Enki should show on the hint, why it has failed. Unlikely to be done soon.

> Red pencil, diskette + pencil

I like the icons, applied and pushed. But, on my screen it is still difficult to recognize red pencil as a pencil, because the icon is small. (I use small system font, so icons are drawn even smaller than 22 px). Could you make v3 icons where red pencil is wider?  As wide as red lines on `Save icon and deleted icon superimposed`  would be good in this case I think. (There are only 1 line and diskette still will be recognizable).

**Comment by vi** [comment]
* Savedel v3:  ![savedel3](https://cloud.githubusercontent.com/assets/173219/6347436/34d445ea-bc29-11e4-829c-d6c2d3e6d86a.png)
* Pencil v3: ![redpencil3](https://cloud.githubusercontent.com/assets/173219/6347442/3ef0b6a8-bc29-11e4-83e1-23881613effd.png)
* Diskette+pencil v3: ![savepencil3](https://cloud.githubusercontent.com/assets/173219/6347450/4c765030-bc29-11e4-8385-0e2aff5d3ed2.png)

**Comment by hlamer** [comment]
Perfect! Applied new icons.
Do you really think insta-edit mode is useful?
