### ISSUE TITLE
Preview dock: horizontal scroll bar flickering

### ISSUE THREAD

**Issue by hlamer** [hlamer/enki#258]
Horizontal scroll bar appears for a short time when updating preview.
Progress bar also flickers.

**Comment by bjones1** [comment]
Hmmm. I'll take a look and see. I would this is should be easy to fix...

**Comment by hlamer** [comment]
I've disabled horizontal scrollbar

**Comment by hlamer** [comment]
Bryan:

> I have several places (such as tables and images CodeChat generates in the preview window) where having a horizontal scroll bar is a must. This was disabled in #258. With the preview sync scroll fixes, could be re-enable this? I assume the flickering is better, since sync has a tolerance included.

**Comment by hlamer** [comment]
Scroll bar appears not because of sync, but because of repainting. It seems like at first Qt tries to pain the dock without scroll bar, then understands, that scroll bar is necessary and repaints the dock again.

**Comment by bjones1** [comment]
Yuck. What OS are you using? On my Mint 16 x32, everything is fine. Perhaps that's because I'm running it in VirtualBox, so the VM's drivers are different?

**Comment by hlamer** [comment]
I think it depends more on document layout and dock widget geometry. I restored horizontal scroll bar. Will try to reproduce it again and document conditions.
