### ISSUE TITLE
E-mail problems; Vim mode discussion.

### ISSUE THREAD

**Issue by vi** [hlamer/enki#265]
Can't reply to to received e-mail normally, including from other `*@tut.by` address:

> Technical details of permanent failure: 
> Google tried to deliver your message, but it was rejected by the server for the recipient domain > tut.by by mx.yandex.ru. [2a02:6b8::89].
> 
> The error that the other server returned was:
> 550 5.7.1 No such user!

Posting the reply here as a fallback:

> Привет!
>
> Я сделал базовую реализацию Vim mode. Зарелизится она еще не совсем скоро, однако уже юзабельна и я даже успел на нее подсесть.
> Предполагаю что тебе это тоже может быть интересно.

Do you want "beeping" and "breaking text" modes in Enki?

Which of the following features (present in Vim, but missing in current Enki) does this "Vim mode" bring?:

1. Search&replace in a selected text block;
2. Filter selected lines though the external program;
3. Ability to work in terminal (e.g. over serial connection, without X server or frame buffer);
4. Jump to matching bracket/quote;
5. Folding;
6. Vertical and horizontal split;
7. Identifier completion across opened files (not just the current file);
8. Macros;
9. vimdiff.

Or it is just Vim-style keyboard interaction, like "15G" instead of "Ctrl+L, 15, Enter"?

**Comment by hlamer** [comment]
When I say `Vim mode`, I mean beeping and breaking text. `15G`, `2dw` etc. Jump to matching bracket on `%` is implemented.

All other features could be implemented in the future, but not as part of `Vim mode`. And, not necessary in vim-like style.

**Comment by vi** [comment]
I think "jump to matching bracket" (also quote or "begin/end" construction, or to "fi" from "if" in Bash, etc.) should be not only in Vim mode, it should be an entry Application shortcuts for users to assign.

The most important Vim feature I would like to see in Enki is vertical/horizontal split, both for the same file and for different files.

The second place is after identifier search in other files. I remember opening additional files in Vim just to bring more identifiers in. Also I remember adding some commented out content to current file in Enki just to populate the list of identifiers. Of course, current file's idetifiers should take priority and it should not slow down Enki.

**Comment by hlamer** [comment]
`Vim mode` is **only** 2 modes. If you don't like it, it seems there are nothing interesting for you(

For other features - open separate issues.

**Comment by hlamer** [comment]
Btw, I surprised you like vim but not vim modes. I think they are amazing. Now I edit code much quicker, than 2 month ago.
