### ISSUE TITLE
Remove keyboard navigation on linter marks

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#268]
When pylint runs, the resulting linter marks acts as bookmarks, so that Alt+PgUp/PgDn navigate through these. Could separate keys be assigned, so that bookmarks stay distinct from linter marks?

**Comment by hlamer** [comment]
Press `Esc` to hide linter marks.

It is difficult to allocate new intuitive shortcuts, and it would be difficult for users to remember them.
I rarely navigate over linter marks. What do you think about removing keyboard shortcuts for them?

**Comment by bjones1** [comment]
I agree -- this is rarely used for me. I'd suggest removing the linter marks keyboard navigation.

Will esc still hide linter marks in vim mode? Also, should this be a toggle (hide / restore linter marks)? It seems a bit odd to hide, but require a save to re-show them.

**Comment by hlamer** [comment]
if keyboard navigation is disabled - I don't see a reason to hide the marks. So, no need to restore.

**Comment by hlamer** [comment]
I've disabled navigation on linter marks. Will test and see if I'm missing it.
