### ISSUE TITLE
Opened files menu structure

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#270]
In the Opened Files dock, a right-click gives a menu, one item of which is "File system", with the only option "rename" in Windows (Unix adds "Make executable"). Why not simply add these to the main menu, instead of putting them in a submenu? It hardly seems worth the extra navigation to add a two-item submenu.

**Comment by hlamer** [comment]
I added the submenu to avoid accidental clicks on this items.

**Comment by bjones1** [comment]
I can see that: making them difficult to access helps protect them. I would think that the users' ability to cancel these operations (press Esc / cancel) would help compensate for accidental clicks.
