### ISSUE TITLE
Outdated keyboard map

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#271]
The keyboard map at https://docs.google.com/spreadsheet/pub?key=0AlY4NZ8uGZGxdF9aeERuSTc5ajMxVVZjOWZCZGpaM3c&output=html is outdated. Would you update? There are a lot of missing entries. Or grant me access and I can edit.

**Comment by hlamer** [comment]
I've granted you access.

**Comment by bjones1** [comment]
Thanks, I've updated the map.
