### ISSUE TITLE
Sorting in the opened files dock

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#272]
I find the options in the context menu (right-click) or in the Settings | General | Opened file list sort mode somewhat confusing. If I click on Sort | File Name, I would expect to see the list be sorted by file name. Instead, it seems that new files are placed above the currently active file if they come before them alphabetically, or below otherwise. So, I see two issues:

1. "Sort" is the wrong term -- it's more a "position (above or below) in which to insert newly opened files" thing. I don't know of a short way to say that, though.
2. Is this really helpful? I'm a bit skeptical that users will care about this. I would always insert a newly opened file below the currently opened file.
3. In the Setting pane, one order is "URI"; in the Sort context menu, its "URL". Both should probably be named "path".

**Comment by hlamer** [comment]
It seems like "File Name" sort mode is broken.

Probably "Sort" is wrong term, but for me it is the most clear term. It is not only about inserting newly opened files. When sort order is changed - whole list shall be resorted.

I think it is hepful. I always use "URI" mode. So, when I have many files from many directories opened, files are grouped according to subdirectories. I think it is much better, than to place files according to opening order.
I never use any other sort modes except default. So, we can think about removing the sort mode setting and leaving only default mode.

"URI" and  "URL" is a bug. Will change to "path"

**Comment by bjones1** [comment]
OK, that's helpful. So: choosing a "sort" item *should* resort the list? If so, I vote for removing the other sort modes, which (as you say) don't seem very helpful.
