### ISSUE TITLE
Too many settings subcategories

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#273]
I feel that the Settings dialog has too many categories. In particular, I think the Editor should be combined into a single item, rather than 6 subitems. Command prompt should be put somewhere else, since it's just one item (perhaps in General?).

**Comment by hlamer** [comment]
What is criteria for "Too many"?
I think now it is obvious, where any particular option is located in Enki dialogue.
When configuring other software, I often end up scanning settings dialogue page by page line by line.

Under-allocated page is not a problem. Over-allocated page is.
https://rodgersnotes.wordpress.com/2010/10/25/google-and-apple-versus-your-companys-application/

**Comment by bjones1** [comment]
I agree that Enki as is does clearly specify where settings are located. I have been annoyed by scrolling through MS Word's endless list of settings. However, I would claim that under-allocated pages are bad, too: they distract users by separating related concepts, requiring multiple clicks to switch back and forth as the user struggles to understand the relationship between these concepts. At a minimum, I think the Edge and Wrap categories should be combined, since they interact. I think several other dialogs (Font, indentation, autocompletion) have so little context they're more easily adjusted when grouped together.

**Comment by hlamer** [comment]
Good point about about Edge and Wrap. Combined!
But I still think that Font, Autocompletion and Indentation are different concepts

**Comment by bjones1** [comment]
OK, thanks!
