### ISSUE TITLE
"Smart" home/end

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#275]
I would like the home key to first move to the beginning of the displayed line, then to the beginning of the document line; likewise for the end key. The idea is taken from Scintilla: http://www.scintilla.org/ScintillaDoc.html#KeyboardCommands, SCI_HOMEWRAP / SCI_LINEENDWRAP messages.

**Comment by hlamer** [comment]
Home key is smart in other way: it goes to first non-space character of the line, then to first character.
It is unlikely, that Scintilla-like behavior will be implemented by me, because I use Wrap lines (default settings).
But, I'm always open for pull requests.

**Comment by bjones1** [comment]
OK. If I add it, I'd add an "extra-smart" option (mirroring Scintilla): home goes to the beginning of the line; on the second press, home moves to the first non-space character; then, on the third press, to the beginning of the line. Does that sound reasonable?

**Comment by hlamer** [comment]
It does

**Comment by bjones1** [comment]
OK. I'll keep this issue open to remind me to work on it when I get a moment.

**Comment by hlamer** [comment]
Implemented in Qutepart
