### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#293]
While editing...

```
CRITICAL:root:Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\bin\..\enki\core\openedfilemodel.py", line 302, in _
onDocumentDataChanged
    index = self.documentIndex( document_ )
  File "C:\Users\bjones\Documents\enki_all\enki\bin\..\enki\core\openedfilemodel.py", line 231, in d
ocumentIndex
    row = self._workspace.sortedDocuments.index( document )
ValueError: None is not in list
```

Andrei, I know you've stopped working on Enki, but still wondered if you could look at this?

**Comment by hlamer** [comment]
I could. But I don't have any ideas how could this happen.
Can you reproduce this bug? What had you done before you saw this exception?

**Comment by bjones1** [comment]
I'll try to do some and record more details...thanks! Closing until then.
