### ISSUE TITLE
FuzzyOpen: File can be opened only when text field is focused

### ISSUE THREAD

**Issue by vi** [hlamer/enki#308]
Sometimes it fails to open when by single click + Enter key.

Navigating to the file solely using keyboard usually works.

**Comment by vi** [comment]
I also expect it to be opened by doule clicking the list below or selecting an entry and pressing Enter.

**Comment by hlamer** [comment]
Single-click opens a file for both exact and fuzzy locator.
When directory is clicked in the exact locator - path is inserted to the text input and the input is focused

**Comment by vi** [comment]
Yes, the problem was it not up-to-date fuzzyopener's Enki.
