### ISSUE TITLE
FuzzyOpen: Enki is frozen during "Loading".

### ISSUE THREAD

**Issue by vi** [hlamer/enki#310]
Pressing Escape hides the locator window, but does not unblock Enki. Only terminating the second Enki process from console unblocks GUI.

**Comment by hlamer** [comment]
I've done some optimizations. Now 
* fuzzy-matching is 6 times quicker
* a process is replaced  with a thread
* thread is terminated synchronously

Now I don't feel any lags when navigating the kernel sources and enki quits quickly and completely.
Please reopen this bug if you feel some lags.
