### ISSUE TITLE
Enki codeChat  and warning no link will be generated with codeChat.

### ISSUE THREAD

**Issue by yehielliv** [hlamer/enki#313]
I upgrade to sphinx 1.3.1 and I frequently get
 WARNING: toctree contains reference to document u'demo' that doesn't have a title: no link will be generated with codeChat.
I've tried to put title with the old way with starts and other suggestions I've found on the web but none is working. The build seems to be unstable.
As far as the all accompnied modules to photon and sphinx all seems to be active with no errors.
the build output is:
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] demo                                                 
Converting demo using the C lexer.

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 50%] demo                                                  
writing output... [100%] index                                                 

generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.

Is there is an issues I'm not aware with Enki and photon 1.3.1?

Thank you.

Elik

**Comment by hlamer** [comment]
@bjones1, would you look at this issue?

**Comment by yehielliv** [comment]
I tried some other title style like
/* ********************************************
   demo.c - Demo file
*********************************************/
and that seems to work nicely and stable.
Not sure still why.

**Comment by bjones1** [comment]
@yehielliv, thanks for trying our CodeChat with Sphinx. Sphinx *requires* a title for any item you include in the toctree. Therefore, you need to include a comment (as you suggested above) with a heading in it, such as:

``` C
// ************************
// demo.c - Demo file
// ************************
```

**Comment by yehielliv** [comment]
@bjones1 
I enjoy using it but my concern is the stability of the environment.
It's open to many interpretations and it's not strict which can lead to non methodical approaches.
Foe example:
When I did the title as suggested I get
// ******************** // demo.c - Demo file // ********************

Only when I did the title as I mentioned before or better this way
**********************
 demo.c - Demo file
**********************

I get the right format.
I hope it will further develop as sphinx upgrades.
Thank you for the nice work that has been done so far.

**Comment by bjones1** [comment]
Would you view this issue on the web, rather than via your e-mail reader? The comment I made earlier shows three lines, not one.

To recap: any file included by Sphinx in the toctree *must* have at least one heading. Here's some additional headings in a C file. There's nothing open to interpretation or unstable; this is consistent behavior.

``` C
/* ***************************
   A heading
   *************************** 
   This shows the use of a heading using a block comment in C or C++. */

// Another heading
// =================
// This is another example of a heading using inline comments.
```
