### ISSUE TITLE
Usability regression: Opening file from deterministic Locator now requires pressing "down" key twice.

### ISSUE THREAD

**Issue by vi** [hlamer/enki#315]
For example, I want to open "AndroidManifest.xml" using deterministic locator.

Old workflow: Ctrl+L, `Andr`, down arrow (select "AndroidManifest.xml" from the list), Enter.

New workflow: Ctrl+L `./Andr`, **twice** down arrow (the first one selects directory path), Enter.

I expect the list entry showing directory path to be skipped.

**Comment by hlamer** [comment]
Thanks, fixed
