### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by yehielliv** [hlamer/enki#317]
Hi,
Just for your attention the link style guide in url
https://pythonhosted.org/CodeChat/docs/tutorial.html#basic-restructuredtext
 in the reference paragraph
in line
The style guide for literate programming. Read this first. 
is not working.
Thank you.

**Comment by bjones1** [comment]
Thanks for pointing this out! Fixed in https://bitbucket.org/bjones/documentation/commits/80c947b6d8ac7ed8e0b89c1b0eb2d8e9fff0f22d.
