### ISSUE TITLE
In replace mode typing erases end-of-line

### ISSUE THREAD

**Issue by vi** [hlamer/enki#318]
Steps to reproduce
---

1. Enter text like this

        abcde
        fghij

2. Put cursor, for example, after `c`

        abc|de
        fghij

3. Enter replace mode

        abc█e
        fghij

4. Type, for example, `12345`

Expected
---

    abc12345█
    fghij

Actual
---

    abc12345█ij

**Comment by hlamer** [comment]
Returned from holidays
