### ISSUE TITLE
FuzzyOpener tries to open the wrong (lowercased) file.

### ISSUE THREAD

**Issue by vi** [hlamer/enki#326]
I opened Enki in a simple Android project with `RedScreenActivity.java` file.

When I open Locator and type `RSA`, it correctly suggests `src/main/java/org/vi_server/red_screen/RedScreenActivity.java` and is able to open it.

But when I type `rsa.java`, it suggests `src/main/java/org/vi_server/red_screen/redscreenactivity.java` (note the lowercase) and shows `[Errno 2] No such file or directory:` when I try to open it.

Expected: showing the same entry as in the first case (with preserved capitalisation).

I want FuzzyOpener to still suggest `RedScreenActivity.java` for `rsa.java`, but with capitalisation preserved.

**Comment by hlamer** [comment]
Oops, was broken during performance optimization.
Fixed, added some tests.
