### ISSUE TITLE
Idea about using fuzzy opener without project whatsoever.

### ISSUE THREAD

**Issue by vi** [hlamer/enki#328]
1. Implement things from #327 (files opened or created gets to fuzzyopener cache);
2. Don't delete files from the cache if they are closed;
3. Add new mode: `p /dev/null` command explicitly turns off scanning filesystem.

Result: I can use fuzzy-open just to switch between already (or previously) opened files. No scanning, yet fuzzy opening.

`/dev/null` seems to be already a "keyword" for Enki for file deletion, so it won't hurt to reuse it (even on Windows, etc.) for a "null project".

**Comment by hlamer** [comment]
Does is make sense to manually switch off scanning? If you don't need it - just ignore.

**Comment by vi** [comment]
1. Project directory may be inappropriate, with many hard-to-scan files;
2. Extra files overload the fuzzyopener results;

Workaround is simple, just create empty directory and specify it as project path. But `p /dev/null` looks more ideomatic.

**Comment by hlamer** [comment]
Still don't understand reason for `/dev/null`.

* If there are many hard-to-scan files - just ignore it. I don't care if my HDD or Enki is working hard in background while the UI is responsive.
* I don't think the files are Extra. Fuzzy Opener exists to search files in a project. If you want just switch files, some new tool, like Fuzzy Switcher might be useful.

**Comment by vi** [comment]
> I don't care if my HDD or Enki is working hard in background while the UI is responsive.

* Example of hard-to-scan file is a file on failed NFS mount. It can bring thread to uninterruptible sleep.
* Enki don't show the list of fuzzyopener suggestions until if finished the scanning.

---

Currently Enki consider only scanned files for fuzzy opener, i.e. there is one source of information for the fuzzy opener to sort.

When opened files are also considered, there will be two sources of information for fuzzy opener:

* Scanned files
* Opened files

If seems to be natural to be able to turn off the first source when it is not meaningful (i.e. in projectless mode).

---

> Fuzzy Switcher

Currently re-opening already opened file means switching to it, so with separate switcher it would feel duplicated.

Also I want opened previoulsy, but now closed files to be still on the list (to avoid keeing numerous opened files just for switcher to keep a tab on)

**Comment by hlamer** [comment]
First version works fine for me. Will be released soon

**Comment by hlamer** [comment]
This comment was for another issue. But similar for this one. Now releasing as is. There are more important features. Will use fuzzy-opener more in the battle and see if project-less mode is useful.
