### ISSUE TITLE
v6.5.0-rc6 Can't find my own torrents using Search

### ISSUE THREAD

**Issue by vi** [hlamer/enki#331]
Typically (i.e. in v6.4.3) as soon as I add a torrent using "Download an external torrent" feature, it immediately becomes searchable in global search.

In v5.6.0-rc6 hovewer I can't find my downloads beeing seeded no matter what keywords I do try.

**Comment by hlamer** [comment]
@vi, are you sure it is Enki bug?

**Comment by vi** [comment]
Sorry, it's for [Tribler](https://github.com/Tribler/tribler).

Both "Create new issue" pages are in my bookmarks.

**Comment by hlamer** [comment]
Also #330
