### ISSUE TITLE
Preview test failures on Linux

### ISSUE THREAD

**Issue by hlamer** [hlamer/enki#335]
Current master
```
======================================================================
FAIL: test_previewCheck19 (test_plugins.test_preview.TestPreview)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/a/code/enki/tests/test_widgets/../base.py", line 92, in execWithArgs
    func(*args)
  File "/home/a/code/enki/tests/test_widgets/../test_plugins/test_preview.py", line 729, in test_previewCheck19
    self.assertTrue(u'<p>content</p>' in webViewContent)
AssertionError: False is not true

======================================================================
FAIL: test_previewCheck20 (test_plugins.test_preview.TestPreview)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/a/code/enki/tests/test_widgets/../base.py", line 92, in execWithArgs
    func(*args)
  File "/home/a/code/enki/tests/test_widgets/../test_plugins/test_preview.py", line 753, in test_previewCheck20
    self.assertTrue(u'<p>content</p>' in webViewContent)
AssertionError: False is not true

======================================================================
FAIL: test_previewCheck21 (test_plugins.test_preview.TestPreview)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/a/code/enki/tests/test_widgets/../base.py", line 92, in execWithArgs
    func(*args)
  File "/home/a/code/enki/tests/test_widgets/../test_plugins/test_preview.py", line 799, in test_previewCheck21
    self.assertTrue(u'<span class="pre">missing.file</span>' in webViewContent)
AssertionError: False is not true

======================================================================
FAIL: test_previewCheck3 (test_plugins.test_preview.TestPreview)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/a/code/enki/tests/test_widgets/../base.py", line 92, in execWithArgs
    func(*args)
  File "/home/a/code/enki/tests/test_widgets/../test_plugins/test_preview.py", line 445, in test_previewCheck3
    self.assertTrue(u'<p>content</p>' in webViewContent)
AssertionError: False is not true

======================================================================
FAIL: test_previewCheck3a (test_plugins.test_preview.TestPreview)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/a/code/enki/tests/test_widgets/../base.py", line 92, in execWithArgs
    func(*args)
  File "/home/a/code/enki/tests/test_widgets/../test_plugins/test_preview.py", line 428, in test_previewCheck3a
    self.assertTrue(u'<p>content</p>' in webViewContent)
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by hlamer** [comment]
@bjones1, would be very good if you could fix it soon. I'd like to release current master with regex and fuzzy open.
Are there some other issues which shall be fixed before release?

**Comment by bjones1** [comment]
I can't reproduce on 32-bit Ubuntu 14. What OS do you use?

I still see old files show up in the fuzzy locator after adding to the ignored files. Could you clear the fuzzy cache if the ignores are changed?

I have a fix for CodeChat I'd like to include, which should be ready in the next few days. But it that doesn't make it, I'm OK.

**Comment by hlamer** [comment]
I found the problem. sphinx-build where running by python3 on my system. But CodeChat wasn't installed for Python3.

**Comment by hlamer** [comment]
Now fuzzy-opener resets cache on settings save. Which files do you ignore? Should this pattern be added to the default list?

**Comment by hlamer** [comment]
I've created branch v15.11 which will wait for your CodeChat fix.
Some resolution about #319 is welcome too.

**Comment by bjones1** [comment]
My changes to CodeChat are done -- v1.2.1 is the latest. I need help packing it for Linux, so I'll ask Yajo, unless you have any other suggestions.

**Comment by bjones1** [comment]
I'll try again on #319. I haven't been able to reproduce it in the past.

**Comment by bjones1** [comment]
@Yajo, would you have time to help me package CodeChat? I've updated the .spec file (see https://bitbucket.org/bjones/documentation/src/bb500b1895a0ae1a39fd3fe8f9e6d534686ad651/python-codechat.spec?at=default&fileviewer=file-view-default), but am not familiar with the rest of the process. Also, do you know have to make this available for more than just Fedora? Any help would be appreciated.

**Comment by Yajo** [comment]
Hello, I've been a lot of time trying to package Enki, but it took forever because I sadly have a very busy schedule.

Finally somebody continued my job from there, because Fedora guys want to set Enki as the default text editor for their LXQt spin. You will probably want to ask Raphael Groner and Julien Enselme, see https://bugzilla.redhat.com/show_bug.cgi?id=1015868 for more info.
