### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by rapgro** [hlamer/enki#344]
Besides the general license GPLv2, some source files have a GPLv3 header. Please include also the full license text for GPLv3 as it requires to do so.
https://www.gnu.org/licenses/gpl.txt

What license counts for the files without any special header at all?

GPL (v2 or later)
-----------------
enki-15.05.0/win/Enki.iss
enki-15.05.0/win/build_exe.bat
enki-15.05.0/win/build_installer.bat
enki-15.05.0/win/hook-CodeChat.py
enki-15.05.0/win/hook-enki.py
enki-15.05.0/win/hook-qutepart.py

GPL (v3 or later)
-----------------
enki-15.05.0/enki/plugins/preview/approx_match.py
enki-15.05.0/tests/test_plugins/test_approx_match.py

GPL (v3 or later) GPL (v3 or later)
-----------------------------------
enki-15.05.0/debian/copyright

Unknown or generated
--------------------
enki-15.05.0/ChangeLog
enki-15.05.0/LICENSE.GPL2
enki-15.05.0/LICENSE.GPL2.html
enki-15.05.0/LICENSE.GPL2.rtf
enki-15.05.0/MANIFEST.in
enki-15.05.0/Makefile
enki-15.05.0/README.md
enki-15.05.0/bin/enki
enki-15.05.0/bin/enki-editor.pyw
enki-15.05.0/contents.rst
enki-15.05.0/debian/changelog
enki-15.05.0/debian/compat
enki-15.05.0/debian/control
enki-15.05.0/debian/docs
enki-15.05.0/debian/pyversions
enki-15.05.0/debian/rules
enki-15.05.0/debian/source/format
enki-15.05.0/debian/watch
enki-15.05.0/doc/conf.py
enki-15.05.0/doc/core/actionmanager.rst
enki-15.05.0/doc/core/config.rst
enki-15.05.0/doc/core/core.rst
enki-15.05.0/doc/core/document.rst
enki-15.05.0/doc/core/filefilter.rst
enki-15.05.0/doc/core/json_wrapper.rst
enki-15.05.0/doc/core/locator.rst
enki-15.05.0/doc/core/mainwindow.rst
enki-15.05.0/doc/core/uisettings.rst
enki-15.05.0/doc/core/workspace.rst
enki-15.05.0/doc/index.rst
enki-15.05.0/doc/lib/buffpopen.rst
enki-15.05.0/doc/lib/htmldelegate.rst
enki-15.05.0/doc/lib/pathcompleter.rst
enki-15.05.0/doc/widgets/colorbutton.rst
enki-15.05.0/doc/widgets/dockwidget.rst
enki-15.05.0/doc/widgets/lineedit.rst
enki-15.05.0/doc/widgets/termwidget.rst
enki-15.05.0/enki/__init__.py
enki-15.05.0/enki/config/enki.default.json
enki-15.05.0/enki/core/__init__.py
enki-15.05.0/enki/core/actionmanager.py
enki-15.05.0/enki/core/config.py
enki-15.05.0/enki/core/core.py
enki-15.05.0/enki/core/defines.py
enki-15.05.0/enki/core/document.py
enki-15.05.0/enki/core/filefilter.py
enki-15.05.0/enki/core/json_wrapper.py
enki-15.05.0/enki/core/locator.py
enki-15.05.0/enki/core/mainwindow.py
enki-15.05.0/enki/core/openedfilemodel.py
enki-15.05.0/enki/core/queued_msg_tool_bar.py
enki-15.05.0/enki/core/uisettings.py
enki-15.05.0/enki/core/workspace.py
enki-15.05.0/enki/example-plugin/helloworld.py
enki-15.05.0/enki/lib/__init__.py
enki-15.05.0/enki/lib/buffpopen.py
enki-15.05.0/enki/lib/future.py
enki-15.05.0/enki/lib/get_console_output.py
enki-15.05.0/enki/lib/htmldelegate.py
enki-15.05.0/enki/lib/pathcompleter.py
enki-15.05.0/enki/main.py
enki-15.05.0/enki/plugins/__init__.py
enki-15.05.0/enki/plugins/appshortcuts/ActionShortcutEditor.ui
enki-15.05.0/enki/plugins/appshortcuts/__init__.py
enki-15.05.0/enki/plugins/appshortcuts/action_shortcut_editor.py
enki-15.05.0/enki/plugins/appshortcuts/actionmodel.py
enki-15.05.0/enki/plugins/cppfileswitch.py
enki-15.05.0/enki/plugins/detectindent.py
enki-15.05.0/enki/plugins/editortoolbar/IndentationDialog.ui
enki-15.05.0/enki/plugins/editortoolbar/__init__.py
enki-15.05.0/enki/plugins/editortoolbar/editortoolbar.py
enki-15.05.0/enki/plugins/filebrowser.py
enki-15.05.0/enki/plugins/helpmenu/UIAbout.ui
enki-15.05.0/enki/plugins/helpmenu/__init__.py
enki-15.05.0/enki/plugins/hideall.py
enki-15.05.0/enki/plugins/lint/Settings.ui
enki-15.05.0/enki/plugins/lint/__init__.py
enki-15.05.0/enki/plugins/lint/pylint.png
enki-15.05.0/enki/plugins/lint/settings_widget.py
enki-15.05.0/enki/plugins/navigator/Settings.ui
enki-15.05.0/enki/plugins/navigator/__init__.py
enki-15.05.0/enki/plugins/navigator/ctags.py
enki-15.05.0/enki/plugins/navigator/dock.py
enki-15.05.0/enki/plugins/openterm.py
enki-15.05.0/enki/plugins/preview/CodeChat_Settings.ui
enki-15.05.0/enki/plugins/preview/Preview.ui
enki-15.05.0/enki/plugins/preview/Sphinx_Settings.ui
enki-15.05.0/enki/plugins/preview/__init__.py
enki-15.05.0/enki/plugins/preview/dtop_initial_diagram.png
enki-15.05.0/enki/plugins/preview/dtop_initial_diagram.vsdx
enki-15.05.0/enki/plugins/preview/preview.py
enki-15.05.0/enki/plugins/preview/preview_sync.py
enki-15.05.0/enki/plugins/preview/sphinx_templates/conf.py
enki-15.05.0/enki/plugins/preview/sphinx_templates/index.rst
enki-15.05.0/enki/plugins/preview/sync_delta.png
enki-15.05.0/enki/plugins/preview/sync_delta.vsdx
enki-15.05.0/enki/plugins/preview/templates/Default
enki-15.05.0/enki/plugins/preview/templates/MathJax
enki-15.05.0/enki/plugins/preview/templates/WhiteOnBlack
enki-15.05.0/enki/plugins/qpartsettings/Autocompletion.ui
enki-15.05.0/enki/plugins/qpartsettings/Eol.ui
enki-15.05.0/enki/plugins/qpartsettings/Font.ui
enki-15.05.0/enki/plugins/qpartsettings/Indentation.ui
enki-15.05.0/enki/plugins/qpartsettings/LongLines.ui
enki-15.05.0/enki/plugins/qpartsettings/__init__.py
enki-15.05.0/enki/plugins/recentfiles.py
enki-15.05.0/enki/plugins/repl/Settings.ui
enki-15.05.0/enki/plugins/repl/__init__.py
enki-15.05.0/enki/plugins/repl/repl.py
enki-15.05.0/enki/plugins/restorepos.py
enki-15.05.0/enki/plugins/searchreplace/SearchWidget.ui
enki-15.05.0/enki/plugins/searchreplace/__init__.py
enki-15.05.0/enki/plugins/searchreplace/controller.py
enki-15.05.0/enki/plugins/searchreplace/searchresultsdock.py
enki-15.05.0/enki/plugins/searchreplace/searchresultsmodel.py
enki-15.05.0/enki/plugins/searchreplace/searchwidget.py
enki-15.05.0/enki/plugins/searchreplace/substitutions.py
enki-15.05.0/enki/plugins/searchreplace/threads.py
enki-15.05.0/enki/plugins/session.py
enki-15.05.0/enki/plugins/vimtutor/__init__.py
enki-15.05.0/enki/plugins/vimtutor/vimtutor.md
enki-15.05.0/enki/plugins/workspace_actions.py
enki-15.05.0/enki/plugins/workspace_commands.py
enki-15.05.0/enki/resources/icons.py
enki-15.05.0/enki/ui/Exception.ui
enki-15.05.0/enki/ui/SaveFiles.ui
enki-15.05.0/enki/ui/UISettings.ui
enki-15.05.0/enki/widgets/colorbutton.py
enki-15.05.0/enki/widgets/dockwidget.py
enki-15.05.0/enki/widgets/lineedit.py
enki-15.05.0/enki/widgets/termwidget.py
enki-15.05.0/icons/_old/EditorBookmark0.png
enki-15.05.0/icons/_old/EditorBookmark1.png
enki-15.05.0/icons/_old/EditorBookmark2.png
enki-15.05.0/icons/_old/EditorBookmark3.png
enki-15.05.0/icons/_old/EditorBookmark4.png
enki-15.05.0/icons/_old/EditorBookmark5.png
enki-15.05.0/icons/_old/EditorBookmark6.png
enki-15.05.0/icons/_old/EditorBookmark7.png
enki-15.05.0/icons/_old/EditorBookmark8.png
enki-15.05.0/icons/_old/EditorBookmark9.png
enki-15.05.0/icons/_old/buildstandard.png
enki-15.05.0/icons/_old/buildwarning.png
enki-15.05.0/icons/_old/completionsignals.png
enki-15.05.0/icons/_old/completionvariables.png
enki-15.05.0/icons/_old/cpp.png
enki-15.05.0/icons/_old/editbreak.png
enki-15.05.0/icons/_old/editdelete.png
enki-15.05.0/icons/_old/editerror.png
enki-15.05.0/icons/_old/explorer.png
enki-15.05.0/icons/_old/filefind.png
enki-15.05.0/icons/_old/form.png
enki-15.05.0/icons/_old/h.png
enki-15.05.0/icons/_old/helptesters.png
enki-15.05.0/icons/_old/icon.icns
enki-15.05.0/icons/_old/mac.png
enki-15.05.0/icons/_old/pbmessages.png
enki-15.05.0/icons/_old/pbwidgets.png
enki-15.05.0/icons/_old/projectadd.png
enki-15.05.0/icons/_old/projectaddtemplate.png
enki-15.05.0/icons/_old/tabconsole.png
enki-15.05.0/icons/_old/todo.png
enki-15.05.0/icons/_old/unix.png
enki-15.05.0/icons/_old/viewhorizontally.png
enki-15.05.0/icons/_old/viewmaximized.png
enki-15.05.0/icons/_old/viewvertically.png
enki-15.05.0/icons/_old/windows.png
enki-15.05.0/icons/_old/zoomin.png
enki-15.05.0/icons/_old/zoomout.png
enki-15.05.0/icons/abbreviation.png
enki-15.05.0/icons/about.png
enki-15.05.0/icons/add.png
enki-15.05.0/icons/addtab.png
enki-15.05.0/icons/assistant.png
enki-15.05.0/icons/backup.png
enki-15.05.0/icons/big-next.png
enki-15.05.0/icons/big-previous.png
enki-15.05.0/icons/bigger.png
enki-15.05.0/icons/bookmark.png
enki-15.05.0/icons/bookmark_add.png
enki-15.05.0/icons/bookmark_remove.png
enki-15.05.0/icons/breakconditiondisable.png
enki-15.05.0/icons/breakconditionenable.png
enki-15.05.0/icons/breakdisable.png
enki-15.05.0/icons/breakenable.png
enki-15.05.0/icons/build.png
enki-15.05.0/icons/builder.png
enki-15.05.0/icons/button-ok.png
enki-15.05.0/icons/clean.png
enki-15.05.0/icons/clear-list.png
enki-15.05.0/icons/clear.png
enki-15.05.0/icons/close-grey.png
enki-15.05.0/icons/close.png
enki-15.05.0/icons/closeall.png
enki-15.05.0/icons/closetab.png
enki-15.05.0/icons/comment.png
enki-15.05.0/icons/compiler.png
enki-15.05.0/icons/console.png
enki-15.05.0/icons/copy.png
enki-15.05.0/icons/cut.png
enki-15.05.0/icons/debugger.png
enki-15.05.0/icons/desktop.png
enki-15.05.0/icons/dll.png
enki-15.05.0/icons/down.png
enki-15.05.0/icons/dynamicfolder.png
enki-15.05.0/icons/edit-clear-rtl.png
enki-15.05.0/icons/edit.png
enki-15.05.0/icons/editclear.png
enki-15.05.0/icons/editsettings.png
enki-15.05.0/icons/empty.png
enki-15.05.0/icons/emptyline.png
enki-15.05.0/icons/enkiicons.qrc
enki-15.05.0/icons/execute.png
enki-15.05.0/icons/file.png
enki-15.05.0/icons/files.png
enki-15.05.0/icons/filesystem.png
enki-15.05.0/icons/filtered.png
enki-15.05.0/icons/folder.png
enki-15.05.0/icons/function-green.png
enki-15.05.0/icons/generate-icons-resource.sh
enki-15.05.0/icons/go-up.png
enki-15.05.0/icons/goto.png
enki-15.05.0/icons/greenfolder.png
enki-15.05.0/icons/help.png
enki-15.05.0/icons/infos.png
enki-15.05.0/icons/internet.png
enki-15.05.0/icons/interpreter.png
enki-15.05.0/icons/kpf.png
enki-15.05.0/icons/kwin.png
enki-15.05.0/icons/languages/cmake.png
enki-15.05.0/icons/languages/d.png
enki-15.05.0/icons/languages/favicon.ico
enki-15.05.0/icons/languages/java.png
enki-15.05.0/icons/languages/lua.png
enki-15.05.0/icons/languages/perl.png
enki-15.05.0/icons/languages/pov.png
enki-15.05.0/icons/languages/python.png
enki-15.05.0/icons/languages/readme.txt
enki-15.05.0/icons/languages/ruby.png
enki-15.05.0/icons/languages/scheme.png
enki-15.05.0/icons/languages/tcl.png
enki-15.05.0/icons/languages/tex.png
enki-15.05.0/icons/less.png
enki-15.05.0/icons/logo/128x128/enki.png
enki-15.05.0/icons/logo/32x32/enki.png
enki-15.05.0/icons/logo/48x48/enki.png
enki-15.05.0/icons/logo/enki.ico
enki-15.05.0/icons/logo/enki.svg
enki-15.05.0/icons/logo/splashscreen.png
enki-15.05.0/icons/macEol.png
enki-15.05.0/icons/misc-blue.png
enki-15.05.0/icons/misc.png
enki-15.05.0/icons/modified-externally-deleted.png
enki-15.05.0/icons/modified-externally-modified.png
enki-15.05.0/icons/modified-externally.png
enki-15.05.0/icons/modules.png
enki-15.05.0/icons/new.png
enki-15.05.0/icons/next.png
enki-15.05.0/icons/open.png
enki-15.05.0/icons/package_applications.png
enki-15.05.0/icons/package_development.png
enki-15.05.0/icons/package_system.png
enki-15.05.0/icons/paste.png
enki-15.05.0/icons/play.png
enki-15.05.0/icons/previous.png
enki-15.05.0/icons/print.png
enki-15.05.0/icons/project.png
enki-15.05.0/icons/project_.png
enki-15.05.0/icons/projectnew.png
enki-15.05.0/icons/projectopen.png
enki-15.05.0/icons/projectrecents.png
enki-15.05.0/icons/qt.png
enki-15.05.0/icons/qt_form.png
enki-15.05.0/icons/qt_gui.png
enki-15.05.0/icons/qtproject.png
enki-15.05.0/icons/quickprint.png
enki-15.05.0/icons/quit.png
enki-15.05.0/icons/qwidget.png
enki-15.05.0/icons/rebuild.png
enki-15.05.0/icons/recents.png
enki-15.05.0/icons/reload.png
enki-15.05.0/icons/remove.png
enki-15.05.0/icons/replace.png
enki-15.05.0/icons/restore.png
enki-15.05.0/icons/save.png
enki-15.05.0/icons/saveall.png
enki-15.05.0/icons/saveas.png
enki-15.05.0/icons/scope.png
enki-15.05.0/icons/search-replace-directory.png
enki-15.05.0/icons/search-replace-opened-files.png
enki-15.05.0/icons/search-replace-project-files.png
enki-15.05.0/icons/search.png
enki-15.05.0/icons/session.png
enki-15.05.0/icons/settings.png
enki-15.05.0/icons/settings_.png
enki-15.05.0/icons/shortcuts.png
enki-15.05.0/icons/sort.png
enki-15.05.0/icons/stop.png
enki-15.05.0/icons/style.png
enki-15.05.0/icons/text.png
enki-15.05.0/icons/translation.png
enki-15.05.0/icons/translations.png
enki-15.05.0/icons/transparent.png
enki-15.05.0/icons/unixEol.png
enki-15.05.0/icons/up.png
enki-15.05.0/icons/up_arrow.png
enki-15.05.0/icons/update.png
enki-15.05.0/icons/user.png
enki-15.05.0/icons/value.png
enki-15.05.0/icons/values.png
enki-15.05.0/icons/variable.png
enki-15.05.0/icons/vim.png
enki-15.05.0/icons/winEol.png
enki-15.05.0/install/enki.desktop
enki-15.05.0/rpm/enki.spec
enki-15.05.0/setup.py
enki-15.05.0/tests/base.py
enki-15.05.0/tests/run_all.py
enki-15.05.0/tests/test_base.py
enki-15.05.0/tests/test_core/test_core.py
enki-15.05.0/tests/test_core/test_detect_eol.py
enki-15.05.0/tests/test_core/test_detect_language.py
enki-15.05.0/tests/test_core/test_filewatcher.py
enki-15.05.0/tests/test_core/test_hideall.py
enki-15.05.0/tests/test_core/test_locator.py
enki-15.05.0/tests/test_core/test_opened_files_dock.py
enki-15.05.0/tests/test_core/test_uisavefiles.py
enki-15.05.0/tests/test_lib/test_future.py
enki-15.05.0/tests/test_plugins/import_fail.py
enki-15.05.0/tests/test_plugins/preview_sync_source_above_target.png
enki-15.05.0/tests/test_plugins/preview_sync_source_above_target.vsdx
enki-15.05.0/tests/test_plugins/preview_sync_source_aligned_target_above.png
enki-15.05.0/tests/test_plugins/preview_sync_source_aligned_target_above.vsdx
enki-15.05.0/tests/test_plugins/preview_sync_source_aligned_target_below.png
enki-15.05.0/tests/test_plugins/preview_sync_source_aligned_target_below.vsdx
enki-15.05.0/tests/test_plugins/preview_sync_source_aligned_target_equal.png
enki-15.05.0/tests/test_plugins/preview_sync_source_aligned_target_equal.vsdx
enki-15.05.0/tests/test_plugins/preview_sync_source_below_target.png
enki-15.05.0/tests/test_plugins/preview_sync_source_below_target.vsdx
enki-15.05.0/tests/test_plugins/test_file_browser.py
enki-15.05.0/tests/test_plugins/test_import_fail.py
enki-15.05.0/tests/test_plugins/test_lint.py
enki-15.05.0/tests/test_plugins/test_navigator.py
enki-15.05.0/tests/test_plugins/test_preview.py
enki-15.05.0/tests/test_plugins/test_preview_sync.py
enki-15.05.0/tests/test_plugins/test_preview_utils.py
enki-15.05.0/tests/test_plugins/test_qpart_settings.py
enki-15.05.0/tests/test_plugins/test_repl.py
enki-15.05.0/tests/test_plugins/test_search.py
enki-15.05.0/tests/test_plugins/test_workspace_commands.py
enki-15.05.0/tests/test_widgets/test_termwidget.py
enki-15.05.0/upstream.sh
enki-15.05.0/win/build-exe.sh
enki-15.05.0/win/build.rst
enki-15.05.0/win/enki-sphinx.spec
enki-15.05.0/win/enki_install.sh
enki-15.05.0/win/portrait-logo.bmp
enki-15.05.0/win/rthook_pyqt4.py
enki-15.05.0/win/sphinx-build.py

**Comment by hlamer** [comment]
Hi, @rapgro!
Are you packaging Enki for some distribution? Why do you care so much about the license?
Is there some strong reason to include legal header to every source file or it is enough to just make all files consistent?

**Comment by Yajo** [comment]
He has taken my job on packaging qutepart and enki officially in Fedora.

**Comment by kkofler** [comment]
Including the license header on every source file is strongly recommended, but not absolutely required, as long as it is clear under what license the sources are. If there is one project license that really applies to all code, it is clear, but if, as in your case, the project claims to be GPL version 2 or later, but some files have headers allowing only version 3 or later, it is not so clear anymore what license the unspecified files are under.

**Comment by bjones1** [comment]
@hlamer, I'm happy to change the license on all the files I've contributed to Enki -- whatever makes this easier is fine with me. Just let me know what you'd like to do.

**Comment by hlamer** [comment]
> He has continued my job on packaging qutepart and enki officially in Fedora.

That's cool! You are welcome!

@rapgro, `/debian/copyright` in the `v15.11.0`.  has GPL2 license.

**Comment by hlamer** [comment]
@bjones1, can I (or you) remove copyright headers from your files so we can set the license globally in the README?

Generally I'd be happy to change license to something like WTFPL or at least BSD. But I'm not sure if Enki is infected by the GPL dependencies.

**Comment by bjones1** [comment]
Will do!

**Comment by bjones1** [comment]
Done.

**Comment by hlamer** [comment]
Thanks, Bryan! Do you mind changing the license in the future?

@rapgro, @kkofler, does it look fine now?

**Comment by bjones1** [comment]
You mean, leave a license off for any future contributions, so that the overall license of Enki will govern it? Certainly!

**Comment by hlamer** [comment]
Bryan, I mean do you mind changing the license to BSD or something similar sometimes?

**Comment by bjones1** [comment]
I'm open to it, but I prefer a dual-licensing model such as that used by http://state-machine.com/licensing/index.html.

**Comment by hlamer** [comment]
@rapgro, @kkofler  can I close the issue? I'm near to release v15.11

**Comment by kkofler** [comment]
Yes, having the global license in one file is sufficient, as long as there aren't any conflicting license headers on individual files. (The recommendation is to put the header on every file, but as long as the licensing status is clear, one global license statement is sufficient.)
