### ISSUE TITLE
Locator bug?

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#346]
I have the directory `dist` in Enki's list of ignored files. The file browser does ignore it, but the locator doesn't -- it will list directories in `dist`. The screen shot shows `dist` missing from the file browser, but showing up in a Locator search.

![image](https://cloud.githubusercontent.com/assets/2125584/11316565/98ebc7ac-8fd1-11e5-816e-08527dbdd5e0.png)

**Comment by hlamer** [comment]
Fixed!

**Comment by bjones1** [comment]
Thanks!
