### ISSUE TITLE
Locator searches open files?

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#347]
It might be nice if the locator would also match in the list of opened files, in case I had a bunch open, making it easier to find one.

**Comment by hlamer** [comment]
@vi also will be happy

**Comment by hlamer** [comment]
@bjones1, @vi, how to implement this feature?
Add new command? i.e. S**w**itch
Add opened files to the project files list? Shall opened files have greater priority? 
Other variants?

**Comment by bjones1** [comment]
My suggestion: add opened files to the list of files that locator searches (I assume this is the project files list?), but with higher priority than the project files (although this could be optional). Nothing else special beyond that.

**Comment by vi** [comment]
In addition to prioritizing opened file, recently used (but now closed) files can also be visible/prioritized.

More debatable thing: recently used, but disappeared files. Maybe they can be on the list, but with lowered priority and displayed in gray.

**Comment by hlamer** [comment]
Idea by @bjones1 is implemented.
@vi, showing recent files requites much more work. Skipping for now.

**Comment by bjones1** [comment]
This is very nice. Thanks! It works great for me.
