### ISSUE TITLE
Floating docks

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#348]
When I make a dock float, all the wonderful shortcut keys don't work. For example, pressing Alt+F doesn't focus the File Browser when it's floating. If I manually click on it with a mouse, Esc doesn't close it, and Ctrl+Enter doesn't focus the editor. I was assuming these should still work...

**Comment by hlamer** [comment]
Hmm. It seems like Qt treats floating dock as separate window with own set of shortcuts.
Bryan, do you often work with floating docks? For me floating docks look not usable anyway.

**Comment by bjones1** [comment]
I don't. I had a neat UI idea that relied on the docks, but for now we can just disable the float. Perhaps in the future I can figure out how to get them working like the non-float dock.
