### ISSUE TITLE
Flake8 frustrations

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#349]
When Enki used PyFlakes, it would flag syntax errors as red, and less important things (incorrect spacing, etc.) as warnings. With flake8, its reports as errors things I consider warnings (a line over 79 characters, for example). Is there any way to return to this more helpful color scheme?

**Comment by hlamer** [comment]
Yes. I also dislike this behavior. I like flake8 output more, but message classification is bad.
There are `W...` codes for warnings and `E...` codes for errors. I don't know why message for >79 line is an error. It is possible to create a mapping which fixes flake8 error code types.

**Comment by bjones1** [comment]
I would suggest treating all F* messages as errors, and all others as warnings (in terms of the color displayed by Enki). That is, F* is red, E*, W*, C*, and N* are all yellow.

**Comment by hlamer** [comment]
For missing `:` after `def` I have a message `E901 Syntax Error: invalid syntax`

**Comment by bjones1** [comment]
Good point. Probably E902 as well, though I'm not sure what error would generate this.

**Comment by hlamer** [comment]
Need to classify Fxxx errors too.

**Comment by bjones1** [comment]
Ugh. I'm avoiding this for now...

**Comment by hlamer** [comment]
@bjones1, beep if you faced incorrect classification again

**Comment by bjones1** [comment]
Thanks! Will do.
