### ISSUE TITLE
Preview is synced even if not visible

### ISSUE THREAD

**Issue by hlamer** [hlamer/enki#352]
While debugging #351 I found that syncTextToPreview() is called and does its job even if Preview is not available for this type of file.

Steps to reproduce:
* Open some file which has preview. i.e. README.md
* Switch to file which doesn't have preview. i.e. Makefile

Bryan, could you check this?

Is it possible to split preview_sync.py onto 2 simler classes: TextToPreviewSync and PreviewToTextSync? Just an idea, I'm not sure if it is possible and if it makes sense.

**Comment by bjones1** [comment]
Oops. I see it.

**Comment by bjones1** [comment]
OK, fixed. Thanks for finding this.

In terms of splitting `preview_sync.py`, that should work. However, I plan on adding features at some point, and will postpone it until then.

**Comment by hlamer** [comment]
Push this to my v15.11.0. And it seems it time to release the version

**Comment by bjones1** [comment]
OK, done. I agree! Lots of improvements and great new features.

**Comment by hlamer** [comment]
Thank you!
