### ISSUE TITLE
Menu keyboard shortcuts

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#355]
Thinking a bit about Enki, I'm concerned that new users will quickly reject the editor: they'll press Alt-F, S and, when the file isn't saved, say "???!!! I need to find a tool I can be productive with." Then, they'll never give Enki a chance to shine.

I'm suggest remapping existing shortcuts so that the traditional keyboard menu shortcuts work. See a first pass at https://docs.google.com/spreadsheets/d/1GftvSaUP4e9e8YYTL0CtFe_LhxL9_XMW9VA2c5F0RjI/pub?output=html#.

**Comment by hlamer** [comment]
Hmm. I never use this menu accelerators, and I very rarely (or never?) see my colleagues use it. If I want so save something when using new software first time I would just press `Ctrl+S`.
First time impression is important. But everyday experience is more important. Now I'm very happy that search panel has keyboard accelerators and dock shortcuts are intuitive.

**Comment by bjones1** [comment]
Closing for now. Perhaps more thoughts later.
