### ISSUE TITLE
Indents with tab

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#356]
I've discussed this before, but can't find the old issue or e-mail trail. I personally find that the way indents are done confusing: if I select several lines such that the cursor is on the beginning of the last line, not only the active selection but that line gets indented as well! Again, thinking of new users, I'm concerned that people might reject Enki if it doesn't support their established workflows. From a logical perspective, if I have the text "hello,\n world\n" selected, I'd expect to see "    hello,\n    world\n", with no extra spaces at the end.

**Comment by hlamer** [comment]
For me it works quite naturally. 
* Cursor is at the beginning of file. Nothing is selected. You indent 1 line
* You press `Shift+Down` - one more line is selected. 2 lines are indented.

Bryan, download please Sublime 3 and check it. Do you like it's behavior more?

**Comment by bjones1** [comment]
Yes, I prefer Sublime text 3 here. That's also the same behavior as Netbeans, Eclipse, MSVC, Spyder, etc. It's what I'm used to...

**Comment by hlamer** [comment]
Fixed in Qutepart

**Comment by bjones1** [comment]
Wow! Thanks so much! This is soooooo much better!
