### ISSUE TITLE
Thoughts on Enki

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#357]
Not really an issue, but more some thoughts: what defines Enki? For me, it is:

- Simple. Instead of millions of menu items and thousands of options, the minimal set of truly useful features.
- Efficient. The entire interface can be rapidly navigated with the keyboard. This makes it easy for power users to be very productive.
- Available. Free for Windows, Linux, Mac. (I should soon have access to a Mac; hopefully, we can build a binary using Pyinstaller).

It's a great editor, and I'm hoping that others will see that as well.

**Comment by hlamer** [comment]
I agree with one clarification. Some features are not accessible from keyboard.
* main menu
* settings dialogue
* preview save action

And I like it as is. Because for rarely used features it is easier to use mouse than remember shortcuts or use Alt-accelerators.

**Comment by bjones1** [comment]
I agree -- not everything should have a shortcut, but all commonly used commands should. I think Enki fulfills this nicely.
