### ISSUE TITLE
File browser shortcut

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#358]
I use the File Browser quite a bit. There's not a shortcut I'm aware of to move the keyboard focus to the project path. When the cursor is there, I would think that the up/down arrow would open the combo box. Instead, I need to use Alt+arrow or F4.

**Comment by hlamer** [comment]
Try `Ctrl+H`.
I agree that the shortcut is not intuitive and difficult to find. But I don't know how to do better.

**Comment by bjones1** [comment]
Thanks. I'd overlooked that. I added it to the user manual.
