### ISSUE TITLE
Missing submenu?

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#360]
On 69dd75e591113e8e637f5283821e40fbc38b717d, going to `Navigation | File Browser` shows an arrow, indicating that a submenu exists, but it doesn't appear. I don't remember what's supposed to be there. Clicking on it does nothing.

**Comment by hlamer** [comment]
History, Back, Forward. The menu items are missing because the file browser hasn't been shown yet

**Comment by bjones1** [comment]
I see. I would suggest hiding this menu until the browser is shown. It seems odd to have a non-functional menu item.

**Comment by bjones1** [comment]
Thanks!
