### ISSUE TITLE
Find in files

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#361]
I would expect find in files to obey the same excludes given `Settings | Settings | Ignored files...`, but it ignore this.

**Comment by hlamer** [comment]
Do you mean `Search in Directory` functionality?
I checked it, ignored files are ignored for me.
What are the steps to reproduce?

**Comment by bjones1** [comment]
Oops, yes, I meant `Sarch in directory`. Since I use Sphinx+CodeChat with output saved in `_build`, I have that directory in my ignored files. When I search, I get results like:

![image](https://cloud.githubusercontent.com/assets/2125584/12832427/7fd36a80-cb5f-11e5-99aa-5b412cff1f30.png)

I'd like all the `build_` results not to appear. Perhaps this is the backslash bug? On Windows, it's `\` but on Unix `/`, and the mismatch is getting past the exclusions?

![image](https://cloud.githubusercontent.com/assets/2125584/12832493/f964878a-cb5f-11e5-9527-af487a0fd488.png)

**Comment by hlamer** [comment]
Ah, I see now. Files were ignored, but not directories

**Comment by bjones1** [comment]
Thanks!
