### ISSUE TITLE
Navigator loses its place on close

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#362]
In the Navigator, if I use the arrow keys to move around, then press Esc to close the dock, then re-open it, the item I last selected is lost -- I have to start at the top of the list again. In the File Browser, closing then re-opening the dock preserves my last selection.

However, I'd suggest something else: automatically move the current selection to the currently highlighted tag.

**Comment by hlamer** [comment]
Now Navigator jumps to current tag whenever `Alt+N` is pressed. Let's see if it is convenient.

**Comment by bjones1** [comment]
I like it! Thanks.
