### ISSUE TITLE
Locator only recognizes Unix-style slashes

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#365]
On Windows, If I look for `..\foo.txt`, I need to enter `../foo.txt`. Using `/` to refer to the root of the current drive doesn't work at all -- no files can be found there.

However, `~/` does work as expected. Using `c:/` works. Directories displayed end with a Unix-style `/` instead of a `\`.

**Comment by hlamer** [comment]
I tried to add windows slashes support, but it introduces too many corner cases. I'm giving up however pull request is welcome.
For now
* `/` at start of a path is interpreted as the current disk root
* Locator title shows unix style path to give and idea that unix style is preferred

**Comment by bjones1** [comment]
OK, sounds good. Thanks for taking a look!
