### ISSUE TITLE
Enki packaged in Fedora!

### ISSUE THREAD

**Issue by Yajo** [hlamer/enki#366]
This is not exactly an issue, but I wanted to let you know that finally [Enki and Qutepart have been officially packaged in Fedora!](https://bugzilla.redhat.com/show_bug.cgi?id=1281876#c31)

It's sad that I could not be able to complete the process, but it's nice that Rephael Groner took it, so here we have it now. :blush:

The "issue" part of this is that you could update the install instructions. I still encourage the team to keep the OBS Fedora package to have a more close to upstream package available for those who want it.

Thanks!

**Comment by hlamer** [comment]
That's amazing!
Thanks @Yajo, @rapgro!

I'll probably keep the package on OBS, but also add a note that it is available in the official repositories.

**Comment by rapgro** [comment]
@lupinix FYI

@hlamer Unfortunately, it's not possible to use the enki menu in LXQt, most of the menu entries are greyed out (why?) and sub menus don't open when moused there.

**Comment by rapgro** [comment]
When to expect Python3 port of Enki? Fedora has big interest to port $everything to Python3.

**Comment by hlamer** [comment]
@rapgro, Python3 port is in progress now. I hope to have stable version in a month or 2
How can I test the bug on LXQt?

**Comment by dglent** [comment]
I use Enki 15.11.0 in Mageia 5 64bit with lxqt 0.9.0 without any problem

**Comment by rapgro** [comment]
Fedora 23 has Qt5.5.1 and LXQt 0.10.0 if you update to latest packages from official repository.

**Comment by dglent** [comment]
Thanks, i've been helped by fedora package to make the rpm for mageia:
http://madb.mageia.org/package/show/application/0/release/cauldron/name/enki

**Comment by hlamer** [comment]
I tried to
* download fedora 23 netinst
* install it on 64bit virtualbox with all default settings
* do `dnf group install lxqt`
* reboot and login to lxqt
* install enki from [my repo](http://software.opensuse.org/download.html?project=home%3Ahlamer%3Aenki&package=enki)

The menu items are not disabled for me.
Which exactly items are disabled? How to reproduce this problem?

**Comment by hlamer** [comment]
I encountered other problem - menu bar is shrunk down. I see only not-enough-space marker and the menu opens vertically. This problem reproduces on both lxqt and gnome. But not on enki master which uses python3-pyqt5 now.

**Comment by Yajo** [comment]
@hlamer see https://bugzilla.redhat.com/show_bug.cgi?id=1292724.

To reproduce the problem, install Enki from Fedora, not from your repo.

**Comment by hlamer** [comment]
Commented in the redhat bugzilla

**Comment by hlamer** [comment]
No icons on dock close button

**Comment by hlamer** [comment]
menubar is fixed in `hotfix-15.11.1` branch

**Comment by hlamer** [comment]
@Yajo, @rapgro, I've released v15.11.1. It contains 2 GUI fixes specially for Fedora. Please migrate to it.

**Comment by rapgro** [comment]
There's no need to notify about new updates in this issue. We use Upstream Release Monitoring, it will automatically open a new report in RedHat Bugzilla.
https://release-monitoring.org/project/8272/

**Comment by rapgro** [comment]
I'm planning to do a prerelease package of upcoming changes. For now I guess version is going to be 15.12.0 or?

**Comment by hlamer** [comment]
I hope the version will be 16.04. Waiting for a few fixes by @bjones1 
And the version will be based on Py3 and Qt5

**Comment by rapgro** [comment]
A pre-release package is currently in updates-testing, it looks great.

> And the version will be based on Py3 and Qt5
:+1:

Will the python2 branch (currently still master) of qutepart then be obsolete? But not sure if someone else needs it in Fedora as a separate library component independent from Enki based now on python3-qt5.

**Comment by hlamer** [comment]
Now both Enki and Qutepart master is Py3. And I'm not going to support Py2 versions.

**Comment by rapgro** [comment]
Very cool! Thanks.

**Comment by rapgro** [comment]
Qutepart 2.2.3 does not build with Python 3. The branch py3 is older than v2.2.3, how to solve?

**Comment by rapgro** [comment]
https://github.com/hlamer/qutepart/issues/21

**Comment by hlamer** [comment]
Use master for both projects

**Comment by rapgro** [comment]
Ah, I confused it. Sorry for the noise. Can we close this issue?

**Comment by hlamer** [comment]
Hi, Fedora guys!
I've just released Enki v16.04.0 and Qutepart v3.0.0. Now projects are based on Python3 and PyQt5.
There are also a lot of improvements. I hope you'll migrate to the new packages

**Comment by dglent** [comment]
Packages are now also available for Mageia (the next version 6).
