### ISSUE TITLE
Highlight all text matched with the selected text

### ISSUE THREAD

**Issue by dglent** [hlamer/enki#369]
I'd like to ask a feature to highlight the selected string.
Now i select a string and i press ctrl+f to highlight the same text in the file
It would be easier when selecting a text to highlight all occurrences in the file.

**Comment by hlamer** [comment]
I use `Ctrl+F` and I like this behavior. With autohighlighting edited code usually looks like this Christmas tree

<img src="http://zdesvsyo.ru/_ph/415/2/243078368.gif"/>

I don't mind if someone added this feature if it is switched off by default.

**Comment by dglent** [comment]
And not blinking the highlighted text of course! :)

**Comment by dglent** [comment]
As using enki for almost a year i have been used of the Ctrl+F to highlight the matched text now and i don't feel the need of this function any more ...
