### ISSUE TITLE
The preview and the main window are not synced on Linux

### ISSUE THREAD

**Issue by dglent** [hlamer/enki#370]
Hi, the preview and the main window are not synced on Linux (Mageia 5)
On Windows 7 it works.

I try some python, html files and the vim tutorial.

**Comment by hlamer** [comment]
Try to install regex package. It is not available in the repositories and therefore not installed by default. But bundled in the Windows installer.

**Comment by dglent** [comment]
Ok, i had the version 2015.07.19, i installed the latest (2015.11.22) and it is ok.
I added also the minimum version in mageia spec

**Comment by hlamer** [comment]
Do you already have version 2015.11.22 in Mageia repositories?
I'd be happy to declare regex dependency for Ubuntu etc but `2015.11.22` will not be available soon(

**Comment by dglent** [comment]
I have just pushed for mageia cauldron (under developpement)
http://svnweb.mageia.org/packages?view=revision&revision=913920

For mageia 5 i have it in my personal repository as it is n't available the package at all:
http://www.mageia-gr.org/rpm/5/x86_64/python-regex-2015.11.22-1mgr5.x86_64.rpm
