### ISSUE TITLE
Running the current git version with python3 - Codechat non available

### ISSUE THREAD

**Issue by dglent** [hlamer/enki#373]
What is the plan for the Preview plugin as the python-codechat package is only available for python2 ?

**Comment by hlamer** [comment]
CodeChat isn't a mandatory dependency. Enki works fine without it but doesn't support literate programming so well.
CodeChat will be ported.

**Comment by bjones1** [comment]
CodeChat is now ported in github. I'll release after getting Enki tested and running on Windows.

**Comment by dglent** [comment]
I installed the git python3 version of codechat and it works ok in enki
Thanks

**Comment by bjones1** [comment]
Thanks for trying! I'll release an update on PyPI soon. Would you be interested in helping me package this for Linux? I have little expertise in this area, unfortunately.

**Comment by dglent** [comment]
Yes i can help, tell me what you would like to test, although i didn't have any problem compiling and installing the the rpm package.

**Comment by bjones1** [comment]
Great! I'd like to package CodeChat for any many Linux distributions as possible. The OpenSUSE Build Service seems the best way to do that. For example, I really like the way Enki is distributed at https://software.opensuse.org/download.html?project=home%3Ahlamer%3Aenki&package=enki. I've worked just a bit toward bringing this up (see https://github.com/bjones1/CodeChat/tree/master/Linux_packaging), but haven't tested or built this. Would you have time to try (and fix) this on OBS?

**Comment by dglent** [comment]
Especialy this period i will not be able to do anything in OBS (i change city and workplace).
I can test on my system although, and i maintain the package for Mageia (enki and codechat).

**Comment by bjones1** [comment]
I understand. If you have time later after moving and transitions are done, I would still appreciate any help at that time. In the present, would you mind sharing the .spec file you used? I can at least add that to my repo.

**Comment by dglent** [comment]
I use this spec file:
https://svnweb.mageia.org/packages/cauldron/python-codechat/current/SPECS/python-codechat.spec?view=markup

**Comment by bjones1** [comment]
Thanks!
