### ISSUE TITLE
Drag and drop on Windows fails

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#379]
Using 4d2ebe4cf7537241ffefe126d8f22fd0c24c1433, drag and drop to open a file simply places a URL to the file in the qutepart window instead of opening a file. Windows 8.1, Py3.4, Qt 5.5.1.

**Comment by hlamer** [comment]
Same behavior on Linux.
Fixed now

**Comment by bjones1** [comment]
Thanks!
