### ISSUE TITLE
MIT-Scheme highlighting

### ISSUE THREAD

**Issue by alexgian** [hlamer/enki#380]
I am surprised that even though you have such nice support for MIT-Scheme, the syntax highlighter is totally inadequate.
I suppose that due to MIT-Scheme's differences:  the weird #| comment |# convention as well as the non standard #!optional argument shebang, standard parsers are quickly defeated.

Is there an easy way to edit the Scheme grammar parsing, or add a new derivative that fixes this?
Many Thanks!

**Comment by hlamer** [comment]
Hi!

Read [this](https://docs.kde.org/stable5/en/applications/katepart/highlight.html) document, then edit [this](https://github.com/hlamer/qutepart/blob/master/qutepart/syntax/data/xml/scheme.xml) file. If you use Linux, this file is located somewhere at `/usr/lib/python..` or `/usr/local/lib/python...`.
Your pull request to Qutepart is welcome!

**Comment by alexgian** [comment]
Thank you so much!

I was having a bit of trouble finding those files.

I hope to have the pull request ready soon!

Best Regards (and huge appreciation for your efforts!)

Alex
