### ISSUE TITLE
Enki freeze

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#381]
Enki froze when I tried to open Enki's .gitignore file. The console output was a lot of repeated `ERROR:qutepart:#pop value is too big 1` lines. I'm using the Python parser, instead of cParser, since I don't have the correct compiler installed on this PC.

The freeze is consistent -- just opening the file does it. I'm using Enki 6bb7209cda4720f27855e4e8b589bc8d3e2c4df4, qutepart 06b1bebef083208b4f8b6eb22f120c19da3e44eb.

**Comment by hlamer** [comment]
I've fixed the freeze. Update qutepart.
But, anyway, you should build the C parser, Python implementation is too slow for real usage.

**Comment by bjones1** [comment]
Thanks. I know -- I'm just about to get a new PC, so didn't want to do the painful compiler install, then do it again in a few days.
