### ISSUE TITLE
v15.11.1: Preview is not visible

### ISSUE THREAD

**Issue by vi** [hlamer/enki#386]
```
Traceback (most recent call last):
  File "/mnt/src/git/enki/bin/../enki/plugins/preview/preview.py", line 398, in run
    self.htmlReady.emit(task.filePath, html, errString, url)
UnboundLocalError: local variable 'html' referenced before assignment
```

**Comment by vi** [comment]
Is not reproducible in master.

**Comment by hlamer** [comment]
But the bug still exists. 
@bjones1, will you have time to check it?
`exepthook` in `main.py` shows an exception as a messagebox.

**Comment by bjones1** [comment]
I'm confused. If the bug can't be reproduced in master, my assumption is that it was fixed by the additional commits. Is there a case where this happens in master?

**Comment by vi** [comment]
If really needed I can try bisecting.

**Comment by hlamer** [comment]
@bjones1, I haven't seen the bug but I see that after [this](https://github.com/hlamer/enki/blob/master/enki/plugins/preview/preview.py#L399) the traceback will happen because `html` is not defined.

**Comment by bjones1** [comment]
Good point. I'll move the emit inside the try/catch. Eventually, I would like to send the exception back to the main thread.

**Comment by hlamer** [comment]
@bjones1, will you have time for this issue in the near future? I'm near to release Py3-Qt5 based Enki

**Comment by bjones1** [comment]
I think so. There are a couple of other nitpicks to fix, I'll also file issues as soon as I can.

**Comment by bjones1** [comment]
Finally, I just pushed an update which addresses this, plus provides some cleanup of the preview plugin.
