### ISSUE TITLE
master: Error message is confusing

### ISSUE THREAD

**Issue by vi** [hlamer/enki#387]
```
PyQt5 not found
Failed to import Qt4 python bindings:
No module named 'PyQt5'
See http://enki-editor.org/install-sources.html
```

1. So Qt5 or Qt4?
2. http://enki-editor.org/install-sources.html is not available
3. The problem was in using Python2 instead of Python3. I think recent change to Python 3 should be mentioned in error message (PyQt5 may be installed for for Python2, but not for Python3).

**Comment by vi** [comment]
I don't see install-sources.html problem to be addressed in the commit.

**Comment by hlamer** [comment]
Ah, missed this.
Now fixed
Thanks
