### ISSUE TITLE
After updating to Python3/Qt5 I see more unnecessary padding in GUI

### ISSUE THREAD

**Issue by vi** [hlamer/enki#388]
Wasted space marked in red:

![screenshot](https://cloud.githubusercontent.com/assets/173219/12951810/35e22ad6-d025-11e5-9207-cde867ecdcd3.png)

It may be system-wide Qt style issue.

How do I make content in Enki more tightly packed, at least as in old Qt4-based Enki?

**Comment by hlamer** [comment]
I've removed some of the padding

**Comment by vi** [comment]
Looks better now. "Open files" pane is OK, but lower "Navigator" panel (not displayed in screenshot) has padding above (between "Open files" and "Navigator"), which is now more noticable compared to "Open files"'s little (even smaller than Qt4's) header.

Old: ![e1](https://cloud.githubusercontent.com/assets/173219/13024488/7855a572-d206-11e5-9c6b-f4645ccbe1ce.png) 
New: ![e2](https://cloud.githubusercontent.com/assets/173219/13024506/9b05cad4-d206-11e5-88d9-38b0f4bce9f5.png)

**Comment by hlamer** [comment]
Actually the padding is smaller. 
![newpaddings](https://cloud.githubusercontent.com/assets/419720/13041680/77eec1d4-d3ca-11e5-992d-0aa999c8d948.png)
![paddings](https://cloud.githubusercontent.com/assets/419720/13041679/77ec3f5e-d3ca-11e5-8bd4-feb007d71845.png)
Red rectangle size is 13 px against 15 px.

**Comment by vi** [comment]
Strange, visually it looks bigger. It can be further decresed to match "Opened Files" title then.

**Comment by hlamer** [comment]
There is a spacer which is used to resize the docks. If spacer is too small, it is difficult to grab it, especially on a laptop touchpad

**Comment by vi** [comment]
Those grabbing dots look little and glued to the above pane, with extra space below the grab area. Actually most of the gray area can't be used for sizing, only for moving the pane.

That's how it would look according to me:

![e2](https://cloud.githubusercontent.com/assets/173219/13050656/e439e66c-d405-11e5-8f16-6ba39d408eb6.png)

Dots line moved 1 pixel down (extending the grabbable area), gray area (that can't be used for moving anyway) shrank.
