### ISSUE TITLE
Linting on .txt files

### ISSUE THREAD

**Issue by rgb-one** [hlamer/enki#390]
When editing .txt files Python linting is applied.

![linting-on-text-file](https://cloud.githubusercontent.com/assets/5672238/12970008/f9ef3e56-d056-11e5-8b1d-482182e5abd2.PNG)

Platform: Windows 10 64-bit
Enki Version: 15.11.1

**Comment by hlamer** [comment]
And also Python highlighting. Only for files which contain `python` in the first line.
Fixed in Qutepart master.
