### ISSUE TITLE
"Settings" window off screen

### ISSUE THREAD

**Issue by rgb-one** [hlamer/enki#391]
My laptop screen is ~14 inches in diameter.

![settings-dialog-off-screen](https://cloud.githubusercontent.com/assets/5672238/12970044/8515cb26-d057-11e5-9a4b-b092fe333397.PNG)

Platform: Windows 10 64 bit
Enki Version: 15.11.1

**Comment by hlamer** [comment]
What is the screen resolution?

**Comment by rgb-one** [comment]
Resolution: 1366 x 768
That is the default/recommended setting for the system

**Comment by hlamer** [comment]
Ah, it seems like the size would be fine, but the window is shifted out of screen. Quite strange. I would recommend to test master, which is based on Qt5, but we don't have Windows build yet and it is inconvenient to install Enki manually

**Comment by bjones1** [comment]
On my 1920x1080 laptop, everything works fine with master. But that's higher resolution that @rgb-one. There might still be a problem at lower resolution.

**Comment by hlamer** [comment]
When I switch my screen to 1024x768 the settings window is centered on the screen and fits fine. On Qt5/master

**Comment by hlamer** [comment]
@bjones1, could you try to set something x 768 on your screen and open the settings?

**Comment by bjones1** [comment]
Will do.

**Comment by bjones1** [comment]
Here's 1366x768 on my laptop using master. I can see the top, but not the button on the bottom. However, I can probably drag it up and get to the buttons, so that seems OK to me.

![image](https://cloud.githubusercontent.com/assets/2125584/13131276/ff42d1d4-d5af-11e5-991e-557483079a45.png)
