### ISSUE TITLE
Unresposive for a bit when file is opened from outside Enki

### ISSUE THREAD

**Issue by rgb-one** [hlamer/enki#393]
The default folder when opening files from outside Enki (ie. opening a file from Windows Explorer) seems to be `C:\Windows\System32`.The implication of this is that Enki is unresponsive for a while when opening a file from outside of explorer or launching Enki with it in the `System32` directory.

Illustration:
**Fig 1.**
![ohjhgoknkk](https://cloud.githubusercontent.com/assets/5672238/13023106/91df7430-d1b3-11e5-8cd8-6112d5bdaa97.gif)

**Comment by hlamer** [comment]
If you navigate file browser to some other path then close and open Enki, does it open in System32 again?

**Comment by rgb-one** [comment]
No changing directory, closing and then reopening Enki doesn't reopen `System32`, it stays on the directory.

![nqhnnk4vs7](https://cloud.githubusercontent.com/assets/5672238/13062879/2e31d28e-d410-11e5-9377-3437aa0d5655.gif)

**Comment by hlamer** [comment]
It seems like the lag happens when FileBrowser loads too many files. It is quite difficult to fix and it won't happen often, because directories with sources doesn't contain so many files.

**Comment by rgb-one** [comment]
I think setting the default directory when opening files from outside Enki to `%HOMEPATH%` instead of `%SYSTEMROOT%\System32` (`C:\Windows\System32`) because it loads less stuff it seems. It loads faster than `C:\Windows\System32` and it's easier to navigate from %HOMEPATH% to desired directory than it is from `C:\Windows\System32`.

**Comment by bjones1** [comment]
Hmmm. Are you running from source or from the WIndows binary? What version?

**Comment by rgb-one** [comment]
Was running from the Windows binary. Enki version 15.11.1.

**Comment by rgb-one** [comment]
I think [this] is the relevant code that needs modification. I was the following modifications would do the trick:

``` python
if not sys.platform.startswith('win'):
            self._dirsModel.setRootPath(os.path.expanduser("~/")) # unix based systems
        else:
            self._dirsModel.setRootPath(os.environ['HOMEDRIVE'] + os.environ['HOMEPATH']) # windows
```

or something more robust.

I haven't tested it so I don't know if it works or not.

[this]: <https://github.com/hlamer/enki/blob/master/enki/plugins/filebrowser.py#L352-L355>
