### ISSUE TITLE
Support for auto-detection of Ruby source code via shebang

### ISSUE THREAD

**Issue by rgb-one** [hlamer/enki#394]
This works fine for bash and python files, however, when opening a ruby file without the `.rb` extension the code is not highlighted. See **Fig 1.**

**Fig 1.**
![screenshot 2016-02-13 00 51 05](https://cloud.githubusercontent.com/assets/5672238/13026193/00c35dce-d1ed-11e5-8605-4439029a7832.png)

**Comment by hlamer** [comment]
Done in Qutepart master
