### ISSUE TITLE
Can't backspace in Locator due to auto-complete

### ISSUE THREAD

**Issue by vi** [hlamer/enki#395]
I currently typed in Locator: `../..`, then began erasing dots: `../.`. Enki auto-completes: `../.hg` (`hg` being selected). I press Backspace again, it erases selected `hg` and auto-completes `hg` again.

Workaround: use mouse or press Backspace fast enough.

**Comment by hlamer** [comment]
Thanks @vi. I've seen the bug a few times but wasn't able to reproduce until now
