### ISSUE TITLE
Crashing fix

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#397]
I'd tested earlier with no problems, but now I'm getting a "RunTime error: wrapped C/C++ object of type Qutepart has been deleted" when I run unit tests which include commit 5793ae46d268e30613cff3901b52800db86f0e1b. Backing out this commit makes the failure go away. Would you check on Linux?

**Comment by hlamer** [comment]
On linux all is fine when recent Qt is used. What is your Qt version?

**Comment by bjones1** [comment]
Qt 5.5.1, SIP 4.17, PtQt 5.5.1, Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)], OS nt, platform Windows 7.

**Comment by hlamer** [comment]
Hmm. I think this crash will not be reproduced in real life. So, if it breaks your tests try to add something like 
`if "test" not in sys.argv[0]:` to fix the tests

**Comment by bjones1** [comment]
OK, will do.
