### ISSUE TITLE
Locator colors

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#399]
I find the color used to highlight a locator entry on Windows is hard to read:

![image](https://cloud.githubusercontent.com/assets/2125584/13367985/5be9f2b6-dcac-11e5-8de8-1ce7ac4df1a3.png)

Would you mind picking a darker color for the font itself?

**Comment by hlamer** [comment]
How does regular item list (i.e. File Browser) look on Windows?
Probably, [html item delegate](https://github.com/hlamer/enki/blob/master/enki/lib/htmldelegate.py) causes problems.
Try to make this list look like FileBrowser by using QPalette but not by hardcoding colors

**Comment by bjones1** [comment]
Here's the file browser:

![image](https://cloud.githubusercontent.com/assets/2125584/13399937/27c917ac-decb-11e5-85d2-97a69f352fbf.png)

which looks fine to me. I think changing the highlighted text color to black should work.

**Comment by hlamer** [comment]
Yes. But do not write `black`. Try to write something like `palette().color(QPalette.HighlightedText)` (Not sure, which constant to use)

**Comment by bjones1** [comment]
Sounds good. I'll let you know as I make progress.
