### ISSUE TITLE
Using the previewer to preview images (png, jpeg)

### ISSUE THREAD

**Issue by rgb-one** [hlamer/enki#401]
As it is now, Enki opens images in text format which isn't usable. Opening images in Enki via the previewer would make things a bit simpler as one doesn't have to change application to view the image. What do you guys think?

**Comment by hlamer** [comment]
I'd prefer [DOTADIW](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well)

@bjones1?

**Comment by bjones1** [comment]
I agree. @rgb-one, I don't see Enki's purpose to open or view images. There are many good viewers out there (I like IrfanView); duplicating that effort seems a waste to me.
