### ISSUE TITLE
Backspace doesn't work when Caps Lock is on

### ISSUE THREAD

**Issue by vi** [hlamer/enki#403]

**Comment by hlamer** [comment]
It does for me. Either in Vim and in normal modes.

**Comment by vi** [comment]
Reproducible even with QPlainTextEdit.

**Comment by hlamer** [comment]
Seems like the problem reproduces only on your system. Are there some
special keyboard settings?
11 апр. 2016 г. 15:28 пользователь "Vitaly Shukela" <
notifications@github.com> написал:

**Comment by vi** [comment]
Maybe.

Special thing is that Caps Lock mode is turned on with Shift+CapsLock, usual CapsLock is input language change.

I expect it's just yet another Qt5 bug.

**Comment by hlamer** [comment]
I hope you'll manage to workaround this problem. Qt5 version has many improvements.
https://github.com/hlamer/enki/issues?q=milestone%3A%22Next+version%22+is%3Aclosed
