### ISSUE TITLE
The color of the imports is "too" red

### ISSUE THREAD

**Issue by dglent** [hlamer/enki#409]
I find that the red color of the import keyword in python is too flashing. 
It doesn't help to read the imported modules (brakes the eyes)

**Comment by dglent** [comment]
Is better now but before before was much better with the pink which made the module names more readable.

**Comment by hlamer** [comment]
Open a pull request for https://github.com/hlamer/qutepart/blob/master/qutepart/syntax/colortheme.py

**Comment by dglent** [comment]
What do you think about this (without bold) ?
            'dsImport':         textFormatClass(color='#b969c3'),
