### ISSUE TITLE
python3-qt5 5.6

### ISSUE THREAD

**Issue by rapgro** [hlamer/enki#411]
When I call enki-16.04.0-2.fc24.noarch with python3-qt5-5.6-1.fc24.x86_64 :

CRITICAL:root:Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/enki/core/openedfilemodel.py", line 293, in _onDocumentOpened
    document.documentDataChanged.connect(self._onDocumentDataChanged)
TypeError: decorated slot has no signature compatible with Document.documentDataChanged[]

From build.log:
…
test_dev_null (test_core.test_opened_files_dock.Rename) ... ERROR
test_dev_null_os_fail (test_core.test_opened_files_dock.Rename) ... ERROR
test_flags (test_core.test_opened_files_dock.Rename) ... ok
test_os_fail (test_core.test_opened_files_dock.Rename) ... ERROR
test_same_path (test_core.test_opened_files_dock.Rename) ... ERROR
test_success (test_core.test_opened_files_dock.Rename) ... ERROR
test_1 (test_core.test_project.Test)
Parse words ... ok
test_1 (test_core.test_uisavefiles.Test) ... ERROR
test_2 (test_core.test_uisavefiles.Test) ... /usr/bin/xvfb-run: line 166: 23461 Segmentation fault      (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1

Downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1332274

**Comment by rdieter** [comment]
In short, is enki known to work with PyQt5-5.6 yet or not?

**Comment by hlamer** [comment]
@rdeiter, I'll be able to check on Wednesday. But I think it works after the fix by @rapgro
