### ISSUE TITLE
Ctrl+V doesn't work when input layout is Russian

### ISSUE THREAD

**Issue by vi** [hlamer/enki#414]
I need to switch to English to paste text.

**Comment by bjones1** [comment]
@vi, what version of Enki (and Qt) are you using? I see https://bugreports.qt.io/browse/QTBUG-32908, which is Qt4 (old Enki).

**Comment by vi** [comment]
Enki says `Version 15.11.1
Uses Qutepart 2.2.3 (with binary parser)`

Maybe Qt version should also be visible in About window?

**Comment by vi** [comment]
Like #403 it also reproducible with QPlainTextEdit, so it may be third party issue.

**Comment by bjones1** [comment]
It's not a bad idea to provide the Qt version -- would you mind submitting this as a separate issue?

Would you consider Qt5? The latest version of Enki uses that.

**Comment by vi** [comment]
I'm using Qt5 with Python3's Enki and it feels buggier than Qt4 (at lest the Debian Stable version of it).

**Comment by bjones1** [comment]
There are two bugs I haven't tracked down yet. A port is always a painful thing. I hope to get current Enki as stable at "old" (Py2/Qt4) Enki! Any bugs you can submit again the new Enki will be helpful. In particular, could you test this with "new" Enki? I hoping to close it as fixed.

**Comment by vi** [comment]
This is new, Qt5-, Python3-based Enki, isn't it?

**Comment by bjones1** [comment]
No, per https://github.com/hlamer/enki/releases, 16.04.0 is the first Py3/Qt5 release.

**Comment by bjones1** [comment]
But I can't explain what you're seeing in /proc/maps. If the Enki source is handy, open a .py file and see if the imports are from PyQt5 or PyQt4...

**Comment by vi** [comment]
I expect it to be version 7d66dd6db54121358004977ed4b1142aad30b193.

Maybe the code for getting version to display in About window does not work in my case?

I run Enki from source tree without a proper installation.

**Comment by bjones1** [comment]
OK, that's the Py3/Qt5 version, then. It's before the 16.04.0 release, hence the title. I assume the same is true for your Qutepart install.

You might consider updating both -- there have been a number of fixes since then.

...but probably nothing that fixes this bug. Sigh.

**Comment by hlamer** [comment]
Yes, copy-pasting in Russian doesn't work for me. Let's hope the bug will be fixed in Qt sometimes.
And @vi, I use v 16.04 every day. It is as stable as previous version for me.
