### ISSUE TITLE
Up and down arrows does not select file in Locator

### ISSUE THREAD

**Issue by vi** [hlamer/enki#45]
When opening a file using Locator, I expect to be able to navigate the file in currently visible list and press Enter to finally open it. Currently pressing down or up arrows makes Locator show main menu (or main menu with only "[f] PATH [LINE]" entry) or do nothing.

If up/down arrows conflict with Locator history, Ctrl/Alt/Shift/Whatever+up/down can be used.

**Comment by hlamer** [comment]
See #315
