### ISSUE TITLE
Enki does not terminate files with a newline unless I explicitly create an empty line

### ISSUE THREAD

**Issue by vi** [hlamer/enki#63]
\n is a line terminator, not separator.

Text should end with \n by default.

Enki should create files ending in "\n" easily (and files without trailing \n less easy, i.e. by opening existing `No newline at end of file` file).

**Comment by hlamer** [comment]
clarification: Vim saves 0-byte file if file was saved just after creation. But if any edit operation was done - EOL is added. So even absolutely empty file saved as one EOL symbol.
Enki now always adds EOL to any text. So, it is impossible to generate 0-byte file with Enki

**Comment by dglent** [comment]
I have remarked this also. I would like to have this option to create a new line at the end.
Now i create it at every time manually when i realise that is missing in diff checks before committing...

@hlamer: could be reviewed to add it even as a non default option?

**Comment by hlamer** [comment]
I don't quite understand how many new lines are necessary. Enki always adds 1 EOL when saving, and strips back when loading. If you see `asdf` on the screen, Enki saves 
```
a@a-desktop ~/tmp $ od -tx1 test.txt
0000000 61 73 64 66 0a
```

**Comment by dglent** [comment]
If there is a new line at the end of the file and the file is edited and saved in enki, the new line at the end is removed and diffs show the message: "\ No newline at end of file"
There is also a pylint message "W292 no newline at the end of file"

**Comment by hlamer** [comment]
If you create new file, type just `x` and save the file, what is the file size on the file system?

**Comment by dglent** [comment]
1 byte

**Comment by hlamer** [comment]
Hmm, very interesting. Could you please debug [this](https://github.com/hlamer/enki/blob/master/enki/core/document.py#L339) and [this](https://github.com/hlamer/qutepart/blob/master/qutepart/__init__.py#L461) code?

**Comment by dglent** [comment]
I cannot reproduce it with git version and python3
it saves a 2 bytes file, ok with the new line. 
I switch definitely to python3 and git version

**Comment by hlamer** [comment]
Hmm. Very interesting problem, since for me and the others py2 also works fine. But let's focus on stabilization py3 version.
